# Generated by Django 2.2.5 on 2020-06-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_worker', '0002_auto_20200301_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv',
            name='csv_file',
            field=models.FileField(null=True, upload_to='media/csv.csv'),
        ),
    ]
